In [1]:
import numpy as np


In [2]:
#create a numpy array of integer from 0 to 10
arr1 = np.arange(11)
print(arr1)


[ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
#create an array of 10 zeros and chamge the 5th value to 1
arr2 = np.zeros(10)
arr2[4] = 1
print(arr2)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
#Generate an array of 10 ones.
arr3 = np.ones(10)
print(arr3)



[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [5]:
#Create a 1D array of 20 equally spaced numbers between 0 and 1
arr4 = np.linspace(0, 1, 20)
print(arr4)


[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [6]:
#Create a 3x3 identity matrix.
arr5 = np.eye(3)
print(arr5)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#Create a 4x4 matrix with values from 0 to 15.
arr6 = np.arange(16).reshape(4, 4)
print(arr6)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [8]:
#Generate a 5x5 matrix with random values.

arr7 = np.random.rand(5, 5)
print(arr7)


[[0.13419663 0.06166743 0.8362412  0.36152324 0.32239434]
 [0.15728395 0.53220089 0.17572484 0.03918057 0.64645461]
 [0.38561334 0.77261349 0.0380203  0.93972011 0.57694063]
 [0.97783501 0.21029362 0.38592437 0.79840459 0.09596214]
 [0.69511522 0.58365608 0.2821309  0.16505672 0.22281973]]


In [12]:
#Reverse the elements of an array.
arr8 = np.array([1, 2, 3, 4, 5])
arr8reversed = arr8[::-1]
print(arr8reversed)



[5 4 3 2 1]


In [10]:
#Flatten a 2D array to 1D.
arr9 = np.array([[1, 2, 3], [4, 5, 6]])
arr9flattened = arr9.flatten()
print(arr9flattened)

[1 2 3 4 5 6]


In [13]:
#extract even number from an array 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
evennumbers = arr[arr % 2 == 0]
print("Even numbers:", evennumbers)

Even numbers: [ 2  4  6  8 10]
